let puns = [`How did I know where you would go next?                 Oh I felt it in my bones!`, `Why are graveyards so noisy?                   Because of all the coffin!`,
    `What? A telephone?               Nah, I'm using a telebone.`, `These aren't all of them.             I've got a skele        -       TON more!`, `I'm not fat. I'm just big boned!`, `What do skeletons say before they begin dining?                     Bone-Appetit!`, `That annoying dog came back and stole more of our bones. He even ran off with Papyrus' left leg!           You could say he didn't leave him with a        leg      to     stand    on!
`, `What do you call a skeleton snake?                            A rattler!`, `What did the skeleton say while riding his Harley Davidson motorcycle?                        I’m bone to be wild!`, `My brother always works himself down to the bone!`, `Why did the skeleton want a friend?                              Because she was feeling bonely`, `What does a skeleton tile his roof with?                               Shin-gles!`, `What do you do if you see a skeleton running across a road?                                    Jump out of your skin and join him!`, `Papyrus' date didn't go well, did it?          Yeah, He only loves every bone in your body...`, `Everytime I hear a skeleton    joke I feel its *in my bones*`, `Skulls are always single because they have no body`, `
These jokes are very bare boned!
`, `you wanna know why skeletons are terrible liars?                                 Everyone can see right through them!`, `A dog stole a skeleton's left leg and left arm the other day.                                                but it's cool he's ALL                   RIGHT                   now!`, `i'm spooked to the bone!`, `What did the skeleton say when an army invaded his country?                          *We're boned!*`, `What do you call a skeleton who presses the door bell?                                      A dead ringer`, `Whats a skeletons favorite weapon?                                                  A bow and MARROW!`, `What is Papyrus's least favorite type of chicken?                                  Boneless!`, 'What do skeletons put under their hotdogs?                                       a Skele-Bun.', `why did the ghost took the elevator?                                to lift his SPIRIT up`, `the skeleton was sick i guess you could say he was sick         to          the                 B   O   N   E`, `What is a skeleton's favorite music band?                        BONE JOVI!`, `Who was the most famous skeleton detective?                                                            Sherlock BONES!`, `what do you call a plate of spaghetti made by a skeleton?                                                 A CREEPYPASTA!`, `How do you make a skeleton uncomfortable?                                     By crossing his BONEdries`, `Why are skeletons bad at math?                                 
They don't have brains!`, `I'm not much for puns, I just don't find them...                   HUMERUS!
Come on, I know I wasn't all that original, but it was funny wasn't it? Come on... THROW         ME      A           BONE`, `What made Michelangelo's skeleton famous?                                            His SKULLtures`];


let overHealReaction = [`Overhealing? Let's try that one again...`, `Bro             .           .           .       `, `it's a beautiful day outside.                    Birds are singing,      flowers are blooming.                   On days like these, kids like you.          .       .        Should be burning in                 H       E       L       L`];


let beforeAttack = [`So it's my turn now...?`];